window.PROFILE_CONTENT = {
  en: {
    documentTitle: {
      home: "The Witch Trial of yorkyang2333",
      dossier: "The Prison Manor | yorkyang2333",
      investigation: "The Investigation | yorkyang2333",
      ledger: "The Daily Record | yorkyang2333",
      verdict: "The Verdict | yorkyang2333"
    },
    brandRole: "CREATIVE SYSTEMS / DEVELOPER DOSSIER",
    skipLink: "Skip to content",
    menu: "Menu",
    close: "Close",
    languageButton: "中文",
    languageLabel: "Switch language",
    nav: {
      home: "Overview",
      dossier: "The Dossier",
      investigation: "Projects",
      ledger: "Activity",
      verdict: "Contact"
    },
    shared: {
      open: "Open",
      github: "View on GitHub",
      external: "Opens in a new tab",
      scroll: "Scroll to continue",
      back: "Back to overview",
      live: "Live from GitHub",
      snapshot: "Static snapshot",
      loading: "Reading the public record...",
      unavailable: "The public record is temporarily unavailable.",
      updated: "Updated",
      stars: "Stars",
      forks: "Forks",
      repos: "Public repos",
      followers: "Followers",
      recentActivity: "Recent activity",
      noActivity: "No recent public activity found.",
      fallbackNote: "Showing the last generated record while GitHub is unavailable.",
      viewAll: "View all investigations"
    },
    home: {
      eyebrow: "THE WITCH TRIAL OF",
      title: "yorkyang2333",
      intro: "A developer dossier for AI systems, creative software, visual-novel technology, anime media, and unusual cross-platform projects.",
      primaryCta: "Open the dossier",
      secondaryCta: "Browse investigations",
      metaOne: "PERSONAL RECORD",
      metaTwo: "SHANGHAI / UTC+8",
      metaThree: "OPEN TO COLLABORATION",
      witnessesEyebrow: "THE WITNESSES",
      witnessesTitle: "Three ways of making",
      witnessesIntro: "Every project begins with a point of view. These three witnesses keep the work human, rigorous, and curious.",
      witnessOne: "Empathy",
      witnessOneRole: "Read the room",
      witnessOneBody: "Interfaces should make room for people, not ask people to make room for the interface.",
      witnessTwo: "Rigor",
      witnessTwoRole: "Follow the thread",
      witnessTwoBody: "Good systems make their assumptions visible and their failure modes recoverable.",
      witnessThree: "Curiosity",
      witnessThreeRole: "Try the strange path",
      witnessThreeBody: "The most useful tools often begin at the edge of two disciplines.",
      routeEyebrow: "THE RECORDS",
      routeTitle: "Choose a thread",
      routeDossier: "The Prison Manor",
      routeDossierBody: "A closer look at the person, craft, and technical instincts behind the record.",
      routeProjects: "The Investigation",
      routeProjectsBody: "Four case files spanning wearable media, visual novels, anime enhancement, and campus vision.",
      routeLedger: "The Daily Record",
      routeLedgerBody: "A live reading of public GitHub activity, refreshed when you open the ledger.",
      routeVerdict: "The Verdict",
      routeVerdictBody: "A direct line for thoughtful collaborations and strange, useful software.",
      courtAlt: "A stained-glass courtroom with a circular trial floor"
    },
    dossier: {
      number: "01",
      eyebrow: "THE PRISON MANOR",
      title: "A maker's record",
      intro: "A working profile kept by Gokucho: part engineer, part toolmaker, always looking for the human shape of a system.",
      recordAlt: "Prisoner record for yorkyang2333",
      portraitAlt: "Portrait of Gokucho",
      portraitCaption: "THE OWL WARDEN / KEEPER OF THE RECORD",
      factsEyebrow: "THE SUBJECT",
      factsTitle: "What the record keeps",
      factLocationLabel: "Location",
      factLocation: "Shanghai, China",
      factFocusLabel: "Focus",
      factFocus: "AI systems · creative software · media runtimes",
      factMethodLabel: "Method",
      factMethod: "Make the complex feel direct",
      factStatusLabel: "Status",
      factStatus: "Open to careful collaboration",
      principleEyebrow: "WORKING PRINCIPLE",
      principleTitle: "Build tools that respect attention.",
      principleBody: "I like software that feels calm in the hand: clear when it succeeds, honest when it fails, and expressive enough to invite a second look. The work moves between engineering and creative practice because the boundary is often where the useful questions live.",
      techEyebrow: "THE MAGIC WITHIN",
      techTitle: "A stack with a reason",
      techBody: "Python · Kotlin · JavaScript · TypeScript · Vue · Swift · Rust · C++ · Ren'Py",
      areasEyebrow: "CURRENT THREADS",
      areasTitle: "Where the work is moving",
      areaOne: "Intelligent tools",
      areaOneBody: "Multimodal interfaces and AI systems that turn complex inputs into useful actions.",
      areaTwo: "Creative runtimes",
      areaTwoBody: "Cross-platform infrastructure for visual novels, media playback, and expressive software.",
      areaThree: "Visual media",
      areaThreeBody: "Anime enhancement and media tools that care about the final frame as much as the pipeline."
    },
    investigation: {
      number: "02",
      eyebrow: "THE INVESTIGATION",
      title: "Follow the threads",
      intro: "Four case files from the manor. Each one starts with a narrow problem and opens into a different kind of system.",
      projectEyebrow: "CASE FILES",
      projectTitle: "Work worth examining",
      projectIntro: "Open a case file to inspect the repository, implementation choices, and the question that started it.",
      projectOneDescription: "A lightweight music client for Android smartwatches.",
      projectTwoDescription: "A Godot-hosted KiriKiri2 runtime with a C++ engine core and native exports.",
      projectThreeDescription: "An Anime4K enhancement plugin for the IINA media player.",
      projectFourDescription: "A multimodal AI research interface for campus parking perception and optimization.",
      projectOneTag: "Wearable media",
      projectTwoTag: "Visual-novel infrastructure",
      projectThreeTag: "Real-time anime enhancement",
      projectFourTag: "Multimodal campus vision",
      githubCta: "Inspect the repository",
      noteEyebrow: "INVESTIGATOR'S NOTE",
      noteTitle: "The thread matters more than the trophy.",
      noteBody: "The interesting part of a project is rarely the final screenshot. It is the path: which constraint was accepted, which one was challenged, and what became possible after the pieces started talking to each other."
    },
    ledger: {
      number: "03",
      eyebrow: "THE DAILY RECORD",
      title: "The record, refreshed",
      intro: "A live reading of public activity from GitHub. The numbers are useful context, never the whole story.",
      statusLabel: "PUBLIC RECORD",
      kpiRepos: "Public repositories",
      kpiFollowers: "Followers",
      kpiStars: "Total stars",
      kpiForks: "Total forks",
      activityEyebrow: "RECENT THREADS",
      activityTitle: "What moved lately",
      repositoriesEyebrow: "OPEN FILES",
      repositoriesTitle: "Recently updated repositories",
      repositoriesIntro: "The latest public repositories returned by GitHub, ordered by update time.",
      fallbackEyebrow: "ARCHIVED SNAPSHOT",
      fallbackTitle: "The last generated record",
      fallbackBody: "These charts remain available when the public API is rate-limited or offline.",
      eventPush: "pushed commits to",
      eventCreate: "created a branch or tag in",
      eventIssues: "opened or updated an issue in",
      eventPullRequest: "opened or updated a pull request in",
      eventWatch: "starred",
      eventDefault: "touched"
    },
    verdict: {
      number: "04",
      eyebrow: "THE VERDICT",
      title: "Collaboration admissible",
      intro: "No witch needs to be found here. Only work worth sharing, questions worth pursuing, and a good reason to build together.",
      artAlt: "Final verdict: collaboration admissible",
      contactEyebrow: "OPEN CHANNELS",
      contactTitle: "Start with a signal",
      contactBody: "The best first message is concrete: a problem, a prototype, an odd constraint, or a question that has stayed interesting longer than expected.",
      emailLabel: "Email",
      socialLabel: "Elsewhere",
      legal: "Unofficial fan-made theme. No affiliation with the rights holders. Magical Girl Witch Trials and its characters belong to their respective rights holders. © 2024 Re,AER LLC. / Acacia."
    },
    footer: {
      mark: "Y / 2333",
      line: "A quiet record of useful, unusual software.",
      top: "Return to top"
    }
  },
  zh: {
    documentTitle: {
      home: "yorkyang2333 的魔女审判档案",
      dossier: "囚徒宅邸 | yorkyang2333",
      investigation: "调查记录 | yorkyang2333",
      ledger: "每日记录 | yorkyang2333",
      verdict: "最终判决 | yorkyang2333"
    },
    brandRole: "创意系统 / 开发者档案",
    skipLink: "跳到主要内容",
    menu: "菜单",
    close: "关闭",
    languageButton: "EN",
    languageLabel: "切换语言",
    nav: {
      home: "总览",
      dossier: "个人档案",
      investigation: "项目调查",
      ledger: "活动记录",
      verdict: "联系方式"
    },
    shared: {
      open: "打开",
      github: "在 GitHub 查看",
      external: "将在新标签页打开",
      scroll: "继续向下阅读",
      back: "返回总览",
      live: "来自 GitHub 的实时记录",
      snapshot: "静态快照",
      loading: "正在读取公开记录……",
      unavailable: "公开记录暂时不可用。",
      updated: "更新于",
      stars: "Star",
      forks: "Fork",
      repos: "公开仓库",
      followers: "关注者",
      recentActivity: "近期活动",
      noActivity: "没有找到近期公开活动。",
      fallbackNote: "GitHub 暂时不可用，当前显示最近生成的记录。",
      viewAll: "查看全部调查记录"
    },
    home: {
      eyebrow: "关于 YORKYANG2333 的",
      title: "魔女审判",
      intro: "一份关于 AI 系统、创意软件、视觉小说技术、动画媒体和跨平台实验项目的开发者档案。",
      primaryCta: "打开个人档案",
      secondaryCta: "浏览项目调查",
      metaOne: "个人记录",
      metaTwo: "中国上海 / UTC+8",
      metaThree: "开放合作",
      witnessesEyebrow: "证 人",
      witnessesTitle: "三种制作方式",
      witnessesIntro: "每个项目都始于一种看法。这三位证人让工作保持有人情味、足够严谨，也一直保有好奇心。",
      witnessOne: "共情",
      witnessOneRole: "先理解现场",
      witnessOneBody: "界面应该为人留出空间，而不是要求人去适应界面。",
      witnessTwo: "严谨",
      witnessTwoRole: "沿着线索追下去",
      witnessTwoBody: "好的系统会让假设清晰可见，也让失败可以被恢复。",
      witnessThree: "好奇",
      witnessThreeRole: "试试不寻常的路径",
      witnessThreeBody: "最有用的工具，常常从两个领域的边界开始。",
      routeEyebrow: "档 案",
      routeTitle: "选择一条线索",
      routeDossier: "囚徒宅邸",
      routeDossierBody: "更近地了解记录背后的人、技术和制作直觉。",
      routeProjects: "调查记录",
      routeProjectsBody: "四份横跨可穿戴媒体、视觉小说、动画增强和校园视觉的案件。",
      routeLedger: "每日记录",
      routeLedgerBody: "打开记录簿，读取来自 GitHub 的公开活动。",
      routeVerdict: "最终判决",
      routeVerdictBody: "为认真合作和有点不寻常但有用的软件，留下一条直接通道。",
      courtAlt: "带有彩色玻璃窗和圆形审判场的法庭"
    },
    dossier: {
      number: "01",
      eyebrow: "囚徒宅邸",
      title: "一份制作者记录",
      intro: "由 Gokucho 保存的工作档案：一半是工程师，一半是工具制作者，一直在寻找系统更贴近人的形状。",
      recordAlt: "yorkyang2333 的囚徒档案",
      portraitAlt: "Gokucho 的肖像",
      portraitCaption: "猫头鹰守卫 / 记录保管者",
      factsEyebrow: "档案对象",
      factsTitle: "记录留下的内容",
      factLocationLabel: "地点",
      factLocation: "中国上海",
      factFocusLabel: "方向",
      factFocus: "AI 系统 · 创意软件 · 媒体运行时",
      factMethodLabel: "方法",
      factMethod: "让复杂的东西变得直接",
      factStatusLabel: "状态",
      factStatus: "开放认真而谨慎的合作",
      principleEyebrow: "工作原则",
      principleTitle: "制作尊重注意力的工具。",
      principleBody: "我喜欢拿在手里很平静的软件：成功时清晰，失败时诚实，又有足够的表达力让人愿意多看一眼。工作在工程和创作之间来回移动，因为真正有用的问题往往就出现在边界上。",
      techEyebrow: "体内的魔法",
      techTitle: "每种技术都有理由",
      techBody: "Python · Kotlin · JavaScript · TypeScript · Vue · Swift · Rust · C++ · Ren'Py",
      areasEyebrow: "当前线索",
      areasTitle: "工作正在前往的地方",
      areaOne: "智能工具",
      areaOneBody: "多模态界面和 AI 系统，把复杂输入转化为有用行动。",
      areaTwo: "创意运行时",
      areaTwoBody: "为视觉小说、媒体播放和表达性软件制作跨平台基础设施。",
      areaThree: "视觉媒体",
      areaThreeBody: "关注最终画面，也关注处理管线的动画增强和媒体工具。"
    },
    investigation: {
      number: "02",
      eyebrow: "调查记录",
      title: "沿着线索追下去",
      intro: "来自宅邸的四份案件。每一份都从一个具体问题开始，最后展开成另一种系统。",
      projectEyebrow: "案件档案",
      projectTitle: "值得仔细查看的工作",
      projectIntro: "打开案件，查看仓库、实现选择，以及最初提出问题的那一刻。",
      projectOneDescription: "面向 Android 智能手表的轻量音乐客户端。",
      projectTwoDescription: "由 Godot 承载、以 C++ 为核心并支持原生导出的 KiriKiri2 运行时。",
      projectThreeDescription: "面向 IINA 媒体播放器的 Anime4K 画质增强插件。",
      projectFourDescription: "用于校园停车感知与优化的多模态 AI 研究界面。",
      projectOneTag: "可穿戴媒体",
      projectTwoTag: "视觉小说基础设施",
      projectThreeTag: "实时动画增强",
      projectFourTag: "多模态校园视觉",
      githubCta: "查看仓库",
      noteEyebrow: "调查员笔记",
      noteTitle: "重要的是线索，不是奖杯。",
      noteBody: "项目最有趣的部分通常不是最后一张截图，而是那条路径：接受了哪个约束，挑战了哪个约束，以及不同部分开始互相对话之后，什么才成为可能。"
    },
    ledger: {
      number: "03",
      eyebrow: "每日记录",
      title: "一份会刷新的记录",
      intro: "来自 GitHub 公开活动的实时读数。数字提供背景，但从来不是完整的故事。",
      statusLabel: "公开记录",
      kpiRepos: "公开仓库",
      kpiFollowers: "关注者",
      kpiStars: "总 Star",
      kpiForks: "总 Fork",
      activityEyebrow: "近期线索",
      activityTitle: "最近发生了什么",
      repositoriesEyebrow: "开放文件",
      repositoriesTitle: "最近更新的仓库",
      repositoriesIntro: "GitHub 返回的最新公开仓库，按更新时间排列。",
      fallbackEyebrow: "存档快照",
      fallbackTitle: "最近生成的记录",
      fallbackBody: "当公开 API 被限流或离线时，这些图表仍然可用。",
      eventPush: "向这个仓库推送了提交",
      eventCreate: "在这个仓库创建了分支或标签",
      eventIssues: "在这个仓库打开或更新了 Issue",
      eventPullRequest: "在这个仓库打开或更新了 Pull Request",
      eventWatch: "收藏了这个仓库",
      eventDefault: "操作了这个仓库"
    },
    verdict: {
      number: "04",
      eyebrow: "最终判决",
      title: "允许合作",
      intro: "这里不需要找出魔女。只需要分享值得分享的工作，追问值得追问的问题，以及一起动手的好理由。",
      artAlt: "最终判决：允许合作",
      contactEyebrow: "开放通道",
      contactTitle: "从一个信号开始",
      contactBody: "最好的第一条消息可以很具体：一个问题、一个原型、一条奇怪的限制，或一个比预期更长久地保持有趣的问题。",
      emailLabel: "邮箱",
      socialLabel: "其他地方",
      legal: "非官方同人主题，与版权方没有关联。《魔法少女魔女审判》及其角色归各自版权方所有。© 2024 Re,AER LLC. / Acacia。"
    },
    footer: {
      mark: "Y / 2333",
      line: "一份关于有用而不寻常软件的安静记录。",
      top: "返回顶部"
    }
  }
};

window.PROJECTS = [
  {
    id: "claudwecho",
    number: "001",
    href: "https://github.com/yorkyang2333/ClaudWecho",
    image: "assets/theme/case-001-claudwecho.svg",
    title: "ClaudWecho",
    descriptionKey: "investigation.projectOneDescription",
    tagKey: "investigation.projectOneTag"
  },
  {
    id: "aetherkiri",
    number: "002",
    href: "https://github.com/AetherKiri/AetherKiri",
    image: "assets/theme/case-002-aetherkiri.svg",
    title: "AetherKiri",
    descriptionKey: "investigation.projectTwoDescription",
    tagKey: "investigation.projectTwoTag"
  },
  {
    id: "iina-anime4k",
    number: "003",
    href: "https://github.com/yorkyang2333/iina-anime4k",
    image: "assets/theme/case-003-iina-anime4k.svg",
    title: "iina-anime4k",
    descriptionKey: "investigation.projectThreeDescription",
    tagKey: "investigation.projectThreeTag"
  },
  {
    id: "campus-vision",
    number: "004",
    href: "https://github.com/yorkyang2333/illegal-parking-detection-webui",
    image: "assets/theme/case-004-campus-vision.svg",
    title: "Multimodal Campus Vision",
    descriptionKey: "investigation.projectFourDescription",
    tagKey: "investigation.projectFourTag"
  }
];

window.SOCIAL_LINKS = [
  { label: "GitHub", href: "https://github.com/yorkyang2333" },
  { label: "X", href: "https://x.com/yorkyang2333" },
  { label: "Instagram", href: "https://www.instagram.com/yorkyang2333" },
  { label: "Reddit", href: "https://www.reddit.com/user/yorkyang2333" }
];
